/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/calculator": {
    /** @description Get all calculations */
    get: operations["getAllCalculations"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Datasensor */
    HealthStatus: {
      /** @enum {string} */
      status: "OK";
      /**
       * @description Number of milliseconds since Epoch time
       * @example 1688612539479
       */
      timestamp: number;
    };
    ErrorModel: {
      message: string;
    };
  };
  responses: {
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["ErrorModel"];
      };
    };
    /** @description Not found error */
    NotFoundError: {
      content: {
        "application/json": components["schemas"]["ErrorModel"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** @description Get all calculations */
  getAllCalculations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CalculatorResult"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
}
